version: '3.8'

services:
  postgres_master:
    image: postgres:15
    container_name: postgres_master
    restart: always
    environment:
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: customer_db
    ports:
      - "5432:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data

  postgres_replica:
    image: postgres:15
    container_name: postgres_replica
    restart: always
    environment:
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: customer_db
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    depends_on:
      - postgres_master
      - postgres_replica
    environment:
      DB_HOST: postgres_master
      DB_PORT: 5432
      DB_USER: pg_user
      DB_PASSWORD: pg_password
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

volumes:
  pg_master_data:
  pg_replica_data:
